services:
  aprsc:
    build:
      context: .
      dockerfile: trackdirect-aprsc.dockerfile
    #ports:
    #  - "14501:14501"
    volumes:
      - "C:/Users/jose-/OneDrive - Estudiantes ITCR/TEC/Semestre 11/Integrador/Proyecto 1/ServidorAPRS/config:/opt/aprsc/etc"

  collector:
    build:
      context: .
      dockerfile: trackdirect-python.dockerfile
    volumes:
      - "C:/Users/jose-/OneDrive - Estudiantes ITCR/TEC/Semestre 11/Integrador/Proyecto 1/ServidorAPRS/config:/root/trackdirect/config"
    command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
    depends_on:
      - "db"
      - "aprsc"

  websocket:
    build:
      context: .
      dockerfile: trackdirect-python.dockerfile
    volumes:
      - "C:/Users/jose-/OneDrive - Estudiantes ITCR/TEC/Semestre 11/Integrador/Proyecto 1/ServidorAPRS/config:/root/trackdirect/config"
    command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
    ports:
      - "8090:8090"
    depends_on:
      - "db"
      - "aprsc"

  cron:
    build:
      context: .
      dockerfile: trackdirect-cron.dockerfile
    volumes:
      - "C:/Users/jose-/OneDrive - Estudiantes ITCR/TEC/Semestre 11/Integrador/Proyecto 1/ServidorAPRS/config:/root/trackdirect/config"
    depends_on:
      - "db"

  web:
    build:
      context: .
      dockerfile: trackdirect-apache.dockerfile
    volumes:
      - "C:/Users/jose-/OneDrive - Estudiantes ITCR/TEC/Semestre 11/Integrador/Proyecto 1/ServidorAPRS/config:/root/trackdirect/config"
      - "./htdocs/public:/root/trackdirect/htdocs/public" # For development
    ports:
      - "8080:80"
    depends_on:
      - "db"

  db:
    build:
      context: .
      dockerfile: trackdirect-db.dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: trackdirect
    volumes:
      - "C:/Users/jose-/OneDrive - Estudiantes ITCR/TEC/Semestre 11/Integrador/Proyecto 1/ServidorAPRS/db:/var/lib/postgresql/data"
    command: -c config_file=/etc/postgresql.conf
    #ports:
    #  - "5432:5432"

  reverseproxy:
    build:
      context: .
      dockerfile: trackdirect-reverseproxy.dockerfile
    ports:
      - "80:80"
    depends_on:
      - "web"
      - "websocket"
