name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build-db:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: lowercase github.repository
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-db.dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-db:latest
            ghcr.io/${{ env.IMAGE_NAME }}-db:${{ github.RUN_ID }}

  docker-build-apache:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: lowercase github.repository
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-apache.dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-apache:latest
            ghcr.io/${{ env.IMAGE_NAME }}-apache:${{ github.RUN_ID }}

  docker-build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: lowercase github.repository
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-python.dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-python:latest
            ghcr.io/${{ env.IMAGE_NAME }}-python:${{ github.RUN_ID }}

  docker-build-aprsc:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: lowercase github.repository
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-aprsc.dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-aprsc:latest
            ghcr.io/${{ env.IMAGE_NAME }}-aprsc:${{ github.RUN_ID }}

  docker-build-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: lowercase github.repository
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: trackdirect-cron.dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-cron:latest
            ghcr.io/${{ env.IMAGE_NAME }}-cron:${{ github.RUN_ID }}
